[package]
name = "dir-step"
version = "0.1.0"
authors = ["R. Tyler Croy <rtyler@brokenco.de>"]
edition = "2018"

[dependencies]
serde_yaml = "~0.8.13"
serde = {version = "~1.0.117", features = ["derive"]}
otto-agent = { path = "../../crates/agent" }
otto-models = { path = "../../crates/models" }
