[package]
name = "otto-models"
version = "0.1.0"
authors = ["R. Tyler Croy <rtyler@brokenco.de>"]
edition = "2018"

[dependencies]
serde = {version = "~1.0.117", features = ["rc", "derive"]}
serde_json = "~1.0.59"
uuid = { version = "~0.8.1", features = ["v4", "serde"]}
